/**
 * Nexora Type Definitions
 * Central type definitions for the study optimization platform
 */

// ============================================
// User Types
// ============================================

export interface User {
  id: string;
  email: string;
  name: string;
  avatar?: string;
  
  // Gamification
  xp: number;
  level: number;
  streak: number;
  longestStreak: number;
  lastStudyDate?: Date;
  
  // Preferences
  dailyGoalHours: number;
  preferredStart: string;
  preferredEnd: string;
  maxBlockMinutes: number;
  breakMinutes: number;
  
  // AI Settings
  aiDifficulty: AIDifficulty;
  focusMode: boolean;
  
  createdAt: Date;
  updatedAt: Date;
}

export type AIDifficulty = 'easy' | 'medium' | 'hard' | 'adaptive';
export type UserLearningLevel = 'iniciante' | 'intermediario' | 'avancado';
export type StudySessionKind = 'AULA' | 'EXERCICIOS' | 'REVISAO' | 'SIMULADO' | 'ANALISE' | 'LIVRE';

// ============================================
// Subject Types
// ============================================

export interface Subject {
  id: string;
  userId: string;
  name: string;
  color: string;
  icon: string;
  studyPrefs?: StudyPreferences;
  area?: string;
  nivel?: string;
  pesoNoExame?: number;
  enemWeight?: number; // 0-1, used for ENEM weighted scheduling
  prerequisitos?: string[];
  topicos?: string[];
  tipo?: string;
  
  // Study parameters
  priority: number;      // 1-10
  difficulty: number;    // 1-10
  targetHours: number;   // Weekly target
  completedHours: number;
  
  // Progress
  totalHours: number;
  sessionsCount: number;
  averageScore: number;
  
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface StudyPreferences {
  hoursPerDay: number;
  daysOfWeek: number[];
  mode: 'random' | 'exam';
  examDate?: string;
  startDate?: string;
  goal?: 'enem' | 'medicina' | 'concurso' | 'outros';
  userLevel?: UserLearningLevel;
}

// ============================================
// Study Block Types
// ============================================

export type StudyBlockType =
  | 'AULA'
  | 'EXERCICIOS'
  | 'REVISAO'
  | 'SIMULADO_AREA'
  | 'SIMULADO_COMPLETO'
  | 'ANALISE';

export interface StudyBlock {
  id: string;
  userId: string;
  subjectId: string;
  subject?: Subject;
  
  // Timing
  date: Date;
  startTime: string;
  endTime: string;
  durationMinutes: number;
  
  // Roadmap metadata
  sessionType?: 'teoria' | 'pratica' | 'revisao' | 'simulado';
  phase?: string;
  area?: string;
  type?: StudyBlockType;
  description?: string;
  sequenceIndex?: number;
  relatedSubjectId?: string;
  topicName?: string;
  pedagogicalStepIndex?: number;
  pedagogicalStepTotal?: number;
  adaptiveScore?: number;
  
  // Status
  status: BlockStatus;
  isBreak: boolean;
  isAutoGenerated: boolean;
  
  createdAt: Date;
  updatedAt: Date;
}

export type BlockStatus = 'scheduled' | 'in-progress' | 'completed' | 'skipped';

// ============================================
// Study Session Types
// ============================================

export interface StudySession {
  id: string;
  userId: string;
  subjectId: string;
  blockId?: string;
  subject?: Subject;
  
  // Timing
  startedAt: Date;
  endedAt?: Date;
  plannedMinutes: number;
  actualMinutes: number;
  
  // Performance
  focusScore: number;      // 0-100
  productivityScore: number; // 0-100
  accuracyRate?: number; // 0-1
  errorRate?: number; // 0-1
  sessionType?: StudySessionKind;
  difficultyScore?: number; // 1-10
  correctAnswers?: number;
  totalQuestions?: number;
  notes?: string;
  xpEarned: number;
  
  createdAt: Date;
}

// ============================================
// Achievement Types
// ============================================

export interface Achievement {
  id: string;
  name: string;
  description: string;
  icon: string;
  xpReward: number;
  condition: AchievementCondition;
  rarity: AchievementRarity;
}

export interface AchievementCondition {
  type: 'streak' | 'hours' | 'sessions' | 'level' | 'subject_complete';
  value: number;
}

export type AchievementRarity = 'common' | 'rare' | 'epic' | 'legendary';

export interface UserAchievement {
  id: string;
  userId: string;
  achievementId: string;
  achievement: Achievement;
  unlockedAt: Date;
}

// ============================================
// Analytics Types
// ============================================

export interface WeeklyStats {
  id: string;
  userId: string;
  weekStart: Date;
  
  totalHours: number;
  sessionsCount: number;
  avgFocusScore: number;
  avgProductivity: number;
  goalsCompleted: number;
  xpEarned: number;
  
  dailyBreakdown: DailyBreakdown[];
}

export interface DailyBreakdown {
  date: string;
  hours: number;
  sessions: number;
  focusScore: number;
}

export interface HeatmapData {
  date: string;
  value: number; // hours studied
  level: 0 | 1 | 2 | 3 | 4; // intensity level
}

export interface TopicProgress {
  topicName: string;
  mastery: number; // 0-100
  accuracyRate: number; // 0-1
  sessionsCount: number;
  lastStudiedAt?: string;
  nextReviewDate?: string;
  disciplineName?: string;
}

export interface SubjectPerformanceProfile {
  subjectId: string;
  subjectName?: string;
  area?: string;
  accuracyRate: number; // 0-1
  errorRate: number; // 0-1
  averageFocusScore: number; // 0-100
  averageProductivityScore: number; // 0-100
  averageDifficultyScore: number; // 1-10
  lastStudiedAt?: string;
  daysWithoutStudy?: number;
  totalSessions: number;
  lessonSessions: number;
  exerciseSessions: number;
  reviewSessions: number;
  simulatedSessions: number;
  weightedNeedScore?: number;
  trend7d?: number;
  topicProgress?: Record<string, TopicProgress>;
}

export interface PerformanceMetricsSnapshot {
  date: string;
  subjectId: string;
  sessionType: StudySessionKind;
  minutes: number;
  accuracyRate: number; // 0-1
  errorRate: number; // 0-1
  focusScore: number; // 0-100
  productivityScore: number; // 0-100
  difficultyScore: number; // 1-10
  topicName?: string;
  blockId?: string;
}

export interface DailyAnalyticsRecord {
  hours: number;
  sessions: number;
  focusScoreAvg?: number;
  productivityScoreAvg?: number;
  accuracyRateAvg?: number;
  bySubject?: Record<
    string,
    {
      hours: number;
      sessions: number;
      accuracyRateAvg?: number;
      focusScoreAvg?: number;
      productivityScoreAvg?: number;
    }
  >;
}

export interface AnalyticsStore {
  daily: Record<string, DailyAnalyticsRecord>;
  performance?: {
    subjects: Record<string, SubjectPerformanceProfile>;
    sessionHistory: PerformanceMetricsSnapshot[];
    topicProgress: Record<string, TopicProgress>;
    lastUpdatedAt?: string;
  };
  scheduleCache?: {
    key?: string;
    generatedAt?: string;
    range?: { startDate: string; endDate: string };
  };
}

// ============================================
// Dashboard Types
// ============================================

export interface DashboardStats {
  weeklyHours: number;
  weeklyGoal: number;
  focusScore: number;
  streak: number;
  level: number;
  xp: number;
  xpToNextLevel: number;
}

export interface TodayPlan {
  blocks: StudyBlock[];
  totalMinutes: number;
  completedMinutes: number;
}

// ============================================
// Planner Types
// ============================================

export interface ScheduleConfig {
  userId: string;
  subjects: Subject[];
  preferredStart: string;
  preferredEnd: string;
  maxBlockMinutes: number;
  breakMinutes: number;
  excludeDays: number[]; // 0-6, Sunday = 0
  startDate?: Date;
  endDate?: Date;
}

export interface GeneratedSchedule {
  blocks: StudyBlock[];
  totalHours: number;
  subjectDistribution: Record<string, number>;
}

// ============================================
// Onboarding Types
// ============================================

export type StudyGoal = 'ENEM' | 'Medicina' | 'Concurso' | 'Escola' | 'Outro';
export type RoutineType = 'manha' | 'tarde' | 'noite' | 'integral';
export type DailyHoursOption = '<1' | '1-2' | '2-4' | '4+';
export type BestTime = 'manha' | 'tarde' | 'noite' | 'madrugada';
export type FatigueProfile = 'sim' | 'nao';
export type LearningStyle = 'video' | 'leitura' | 'exercicios' | 'misto';

export interface OnboardingAnswers {
  study_goal: StudyGoal;
  routine_type: RoutineType;
  daily_hours: DailyHoursOption;
  best_time: BestTime;
  fatigue_profile: FatigueProfile;
  learning_style: LearningStyle;
  study_days: 3 | 4 | 5 | 6 | 7;
}

export interface UserProfileConfig {
  default_start_time: string;
  block_duration: number;
  intensity_level: 'light' | 'standard' | 'high';
  active_days: number[];
  practice_weight: number;
  focus_subjects: string[];
}

export interface UserProfileDTO extends OnboardingAnswers, UserProfileConfig {
  id?: string;
  userId: string;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface OnboardingResult {
  profile: UserProfileDTO;
  subjects: Subject[];
  schedule: GeneratedSchedule;
  studyPrefs: StudyPreferences;
}

// ============================================
// Preset Wizard Types
// ============================================

export type BestTimeWindow = 'manha' | 'tarde' | 'noite' | 'misto';
export type FocusDuration = 25 | 50 | 90 | 120;
export type BreakDuration = 5 | 10 | 15 | 20;
export type WeekdayKey = 'dom' | 'seg' | 'ter' | 'qua' | 'qui' | 'sex' | 'sab';
export type DailyHoursByWeekday = Record<WeekdayKey, number>;

export interface PresetWizardAnswers {
  dailyHoursByWeekday: DailyHoursByWeekday;
  bestTime: BestTimeWindow;
  availableStart: string;
  availableEnd: string;
  focusMinutes: FocusDuration;
  breakMinutes: BreakDuration;
  targetDailyHours: number;
  goal: 'enem' | 'medicina' | 'concurso' | 'outros';
  examDate?: string;
  startDate?: string;
}

export interface UserSettings {
  name: string;
  email: string;
  avatar?: string;
  dailyGoalHours: number;
  dailyHoursByWeekday?: DailyHoursByWeekday;
  preferredStart: string;
  preferredEnd: string;
  maxBlockMinutes: number;
  breakMinutes: number;
  excludeDays: number[];
  aiDifficulty: 'easy' | 'medium' | 'hard' | 'adaptive';
  focusMode: boolean;
  autoSchedule: boolean;
  smartBreaks: boolean;
  dailyReminder: boolean;
  streakReminder: boolean;
  achievementAlerts: boolean;
  weeklyReport: boolean;
  alarmSound?: 'pulse' | 'beep' | 'chime' | 'soft';
  examDate?: string;
}

// ============================================
// UI Types
// ============================================

export interface NavItem {
  id: string;
  label: string;
  icon: string;
  href: string;
}

export interface ChartDataPoint {
  name: string;
  value: number;
  color?: string;
}

export interface ToastMessage {
  id: string;
  type: 'success' | 'error' | 'warning' | 'info';
  message: string;
  duration?: number;
}

export type AppNotificationType =
  | 'daily'
  | 'streak'
  | 'weekly'
  | 'achievement'
  | 'system';

export interface AppNotification {
  id: string;
  type: AppNotificationType;
  title: string;
  message?: string;
  url?: string;
  createdAt: string;
  read: boolean;
}
