import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { Prisma } from '@prisma/client';
import { prisma } from '@/lib/prisma';
import { authOptions } from '@/lib/auth';

const TRACKED_KEYS = [
  'subjects',
  'plannerBlocks',
  'analytics',
  'studyPrefs',
  'userSettings',
  'scheduleRange',
  'dailyLimits',
  'firstCycleAllSubjects',
] as const;

type TrackedKey = (typeof TRACKED_KEYS)[number];
type ProgressPayload = Partial<Record<TrackedKey, Prisma.JsonValue>>;

const isRecord = (value: unknown): value is Record<string, unknown> => {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
};

const pickTrackedKeys = (input: Record<string, unknown>): ProgressPayload => {
  const payload: ProgressPayload = {};

  for (const key of TRACKED_KEYS) {
    if (!(key in input)) continue;
    const value = input[key];
    if (value === undefined) continue;
    payload[key] = value as Prisma.JsonValue;
  }

  return payload;
};

const serializeSubject = (subject: {
  id: string;
  userId: string;
  name: string;
  color: string;
  icon: string;
  priority: number;
  difficulty: number;
  targetHours: number;
  completedHours: number;
  totalHours: number;
  sessionsCount: number;
  averageScore: number;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}) => ({
  ...subject,
  createdAt: subject.createdAt.toISOString(),
  updatedAt: subject.updatedAt.toISOString(),
});

const serializeBlock = (block: {
  id: string;
  userId: string;
  subjectId: string;
  date: Date;
  startTime: string;
  endTime: string;
  durationMinutes: number;
  type: string | null;
  description: string | null;
  sequenceIndex: number | null;
  relatedSubjectId: string | null;
  status: string;
  isBreak: boolean;
  isAutoGenerated: boolean;
  originalDate: Date | null;
  completedAt: Date | null;
  rescheduleCount: number;
  createdAt: Date;
  updatedAt: Date;
  subject: {
    id: string;
    userId: string;
    name: string;
    color: string;
    icon: string;
    priority: number;
    difficulty: number;
    targetHours: number;
    completedHours: number;
    totalHours: number;
    sessionsCount: number;
    averageScore: number;
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
  };
}) => ({
  ...block,
  date: block.date.toISOString(),
  originalDate: block.originalDate ? block.originalDate.toISOString() : null,
  completedAt: block.completedAt ? block.completedAt.toISOString() : null,
  createdAt: block.createdAt.toISOString(),
  updatedAt: block.updatedAt.toISOString(),
  subject: serializeSubject(block.subject),
});

export async function GET() {
  try {
    const session = await getServerSession(authOptions);
    const userId = session?.user?.id;

    if (!userId) {
      return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    }

    const snapshot = await prisma.userProgressSnapshot.findUnique({
      where: { userId },
      select: {
        payload: true,
        updatedAt: true,
      },
    });

    if (snapshot && isRecord(snapshot.payload)) {
      return NextResponse.json({
        success: true,
        source: 'snapshot',
        updatedAt: snapshot.updatedAt.toISOString(),
        data: pickTrackedKeys(snapshot.payload),
      });
    }

    const [subjects, plannerBlocks] = await Promise.all([
      prisma.subject.findMany({
        where: { userId },
        orderBy: [
          { priority: 'desc' },
          { name: 'asc' },
        ],
      }),
      prisma.studyBlock.findMany({
        where: { userId },
        include: { subject: true },
        orderBy: [
          { date: 'asc' },
          { startTime: 'asc' },
        ],
      }),
    ]);

    const fallbackPayload: ProgressPayload = {
      subjects: subjects.map(serializeSubject) as unknown as Prisma.JsonValue,
      plannerBlocks: plannerBlocks.map(serializeBlock) as unknown as Prisma.JsonValue,
    };

    return NextResponse.json({
      success: true,
      source: 'db-fallback',
      data: fallbackPayload,
    });
  } catch (error) {
    console.error('Progress GET error:', error);
    return NextResponse.json(
      { success: false, error: 'Falha ao carregar progresso da conta.' },
      { status: 500 }
    );
  }
}

export async function PUT(request: Request) {
  try {
    const session = await getServerSession(authOptions);
    const userId = session?.user?.id;

    if (!userId) {
      return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json().catch(() => null);
    const incoming = isRecord(body) && isRecord(body.data) ? body.data : body;

    if (!isRecord(incoming)) {
      return NextResponse.json(
        { success: false, error: 'Payload invalido para sincronizacao de progresso.' },
        { status: 400 }
      );
    }

    const payload = pickTrackedKeys(incoming);

    if (Object.keys(payload).length === 0) {
      return NextResponse.json(
        { success: false, error: 'Nenhuma chave valida para sincronizar.' },
        { status: 400 }
      );
    }

    const snapshot = await prisma.userProgressSnapshot.upsert({
      where: { userId },
      update: {
        payload: payload as Prisma.InputJsonValue,
      },
      create: {
        userId,
        payload: payload as Prisma.InputJsonValue,
      },
      select: {
        updatedAt: true,
      },
    });

    return NextResponse.json({
      success: true,
      updatedAt: snapshot.updatedAt.toISOString(),
    });
  } catch (error) {
    console.error('Progress PUT error:', error);
    return NextResponse.json(
      { success: false, error: 'Falha ao salvar progresso da conta.' },
      { status: 500 }
    );
  }
}
