import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { Prisma } from '@prisma/client';
import { prisma } from '@/lib/prisma';
import { authOptions } from '@/lib/auth';

const TRACKED_STORE_KEYS = [
  'nexora_subjects',
  'nexora_planner_blocks',
  'nexora_analytics',
  'nexora_study_prefs',
  'nexora_user_settings',
  'nexora_schedule_range',
  'nexora_daily_limits',
  'nexora_first_cycle_all_subjects',
  'nexora_onboarding',
  'nexora_session_timers',
  'nexora_backlog_last_auto_run_day',
] as const;

type TrackedStoreKey = (typeof TRACKED_STORE_KEYS)[number];
type StorePayload = Partial<Record<TrackedStoreKey, Prisma.JsonValue>>;

type DeleteMode = 'snapshot' | 'keys' | 'onboarding' | 'progress';

const trackedStoreKeySet = new Set<string>(TRACKED_STORE_KEYS);

const LEGACY_KEY_MAP: Record<string, TrackedStoreKey> = {
  subjects: 'nexora_subjects',
  plannerBlocks: 'nexora_planner_blocks',
  analytics: 'nexora_analytics',
  studyPrefs: 'nexora_study_prefs',
  userSettings: 'nexora_user_settings',
  scheduleRange: 'nexora_schedule_range',
  dailyLimits: 'nexora_daily_limits',
  firstCycleAllSubjects: 'nexora_first_cycle_all_subjects',
  onboarding: 'nexora_onboarding',
  sessionTimers: 'nexora_session_timers',
  lastBacklogAutoRunDay: 'nexora_backlog_last_auto_run_day',
};

const isRecord = (value: unknown): value is Record<string, unknown> => {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
};

const isTrackedStoreKey = (value: string): value is TrackedStoreKey => {
  return trackedStoreKeySet.has(value);
};

const normalizePayload = (value: unknown): StorePayload => {
  if (!isRecord(value)) return {};

  const normalized: StorePayload = {};

  for (const [rawKey, rawValue] of Object.entries(value)) {
    if (rawValue === undefined) continue;

    if (isTrackedStoreKey(rawKey)) {
      normalized[rawKey] = rawValue as Prisma.JsonValue;
      continue;
    }

    const mappedKey = LEGACY_KEY_MAP[rawKey];
    if (mappedKey) {
      normalized[mappedKey] = rawValue as Prisma.JsonValue;
    }
  }

  return normalized;
};

const parseSnapshotPayload = (payload: Prisma.JsonValue | null): StorePayload => {
  if (!payload || !isRecord(payload)) return {};
  return normalizePayload(payload);
};

const serializeSubject = (subject: {
  id: string;
  userId: string;
  name: string;
  color: string;
  icon: string;
  priority: number;
  difficulty: number;
  targetHours: number;
  completedHours: number;
  totalHours: number;
  sessionsCount: number;
  averageScore: number;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}) => ({
  ...subject,
  createdAt: subject.createdAt.toISOString(),
  updatedAt: subject.updatedAt.toISOString(),
});

const serializeBlock = (block: {
  id: string;
  userId: string;
  subjectId: string;
  date: Date;
  startTime: string;
  endTime: string;
  durationMinutes: number;
  type: string | null;
  description: string | null;
  sequenceIndex: number | null;
  relatedSubjectId: string | null;
  status: string;
  isBreak: boolean;
  isAutoGenerated: boolean;
  originalDate: Date | null;
  completedAt: Date | null;
  rescheduleCount: number;
  createdAt: Date;
  updatedAt: Date;
  subject: {
    id: string;
    userId: string;
    name: string;
    color: string;
    icon: string;
    priority: number;
    difficulty: number;
    targetHours: number;
    completedHours: number;
    totalHours: number;
    sessionsCount: number;
    averageScore: number;
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
  };
}) => ({
  ...block,
  date: block.date.toISOString(),
  originalDate: block.originalDate ? block.originalDate.toISOString() : null,
  completedAt: block.completedAt ? block.completedAt.toISOString() : null,
  createdAt: block.createdAt.toISOString(),
  updatedAt: block.updatedAt.toISOString(),
  subject: serializeSubject(block.subject),
});

export async function GET() {
  try {
    const session = await getServerSession(authOptions);
    const userId = session?.user?.id;

    if (!userId) {
      return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    }

    const snapshot = await prisma.userProgressSnapshot.findUnique({
      where: { userId },
      select: {
        payload: true,
        updatedAt: true,
      },
    });

    if (snapshot) {
      return NextResponse.json({
        success: true,
        source: 'snapshot',
        updatedAt: snapshot.updatedAt.toISOString(),
        data: parseSnapshotPayload(snapshot.payload),
      });
    }

    const [subjects, plannerBlocks] = await Promise.all([
      prisma.subject.findMany({
        where: { userId },
        orderBy: [{ priority: 'desc' }, { name: 'asc' }],
      }),
      prisma.studyBlock.findMany({
        where: { userId },
        include: { subject: true },
        orderBy: [{ date: 'asc' }, { startTime: 'asc' }],
      }),
    ]);

    const fallbackPayload: StorePayload = {
      nexora_subjects: subjects.map(serializeSubject) as unknown as Prisma.JsonValue,
      nexora_planner_blocks: plannerBlocks.map(serializeBlock) as unknown as Prisma.JsonValue,
    };

    return NextResponse.json({
      success: true,
      source: 'db-fallback',
      data: fallbackPayload,
    });
  } catch (error) {
    console.error('Progress GET error:', error);
    return NextResponse.json(
      { success: false, error: 'Falha ao carregar progresso da conta.' },
      { status: 500 }
    );
  }
}

export async function PUT(request: Request) {
  try {
    const session = await getServerSession(authOptions);
    const userId = session?.user?.id;

    if (!userId) {
      return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json().catch(() => null);
    const incoming = isRecord(body) && isRecord(body.data) ? body.data : body;

    const incomingPayload = normalizePayload(incoming);

    if (Object.keys(incomingPayload).length === 0) {
      return NextResponse.json(
        { success: false, error: 'Nenhuma chave valida para sincronizar.' },
        { status: 400 }
      );
    }

    const existing = await prisma.userProgressSnapshot.findUnique({
      where: { userId },
      select: { payload: true },
    });

    const mergedPayload = {
      ...parseSnapshotPayload(existing?.payload ?? null),
      ...incomingPayload,
    };

    const snapshot = await prisma.userProgressSnapshot.upsert({
      where: { userId },
      update: {
        payload: mergedPayload as Prisma.InputJsonValue,
      },
      create: {
        userId,
        payload: mergedPayload as Prisma.InputJsonValue,
      },
      select: {
        updatedAt: true,
      },
    });

    return NextResponse.json({
      success: true,
      updatedAt: snapshot.updatedAt.toISOString(),
    });
  } catch (error) {
    console.error('Progress PUT error:', error);
    return NextResponse.json(
      { success: false, error: 'Falha ao salvar progresso da conta.' },
      { status: 500 }
    );
  }
}

export async function DELETE(request: Request) {
  try {
    const session = await getServerSession(authOptions);
    const userId = session?.user?.id;

    if (!userId) {
      return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json().catch(() => ({}));
    const parsedBody = isRecord(body) ? body : {};
    const mode =
      typeof parsedBody.mode === 'string' &&
      ['snapshot', 'keys', 'onboarding', 'progress'].includes(parsedBody.mode)
        ? (parsedBody.mode as DeleteMode)
        : 'snapshot';

    if (mode === 'progress') {
      await prisma.$transaction([
        prisma.userProgressSnapshot.deleteMany({ where: { userId } }),
        prisma.studySession.deleteMany({ where: { userId } }),
        prisma.performanceMetrics.deleteMany({ where: { userId } }),
        prisma.topicProgress.deleteMany({ where: { userId } }),
        prisma.studyBlock.deleteMany({ where: { userId } }),
        prisma.subject.deleteMany({ where: { userId } }),
        prisma.weeklyStats.deleteMany({ where: { userId } }),
      ]);

      return NextResponse.json({ success: true, mode: 'progress' });
    }

    const keysToRemoveRaw =
      mode === 'onboarding'
        ? (['nexora_onboarding'] as string[])
        : mode === 'keys' && Array.isArray(parsedBody.keys)
          ? parsedBody.keys.filter((key): key is string => typeof key === 'string')
          : [];

    const keysToRemove = keysToRemoveRaw.filter(isTrackedStoreKey);

    if (keysToRemove.length === 0) {
      await prisma.userProgressSnapshot.deleteMany({ where: { userId } });
      return NextResponse.json({ success: true, mode: 'snapshot' });
    }

    const existing = await prisma.userProgressSnapshot.findUnique({
      where: { userId },
      select: { payload: true },
    });

    if (!existing) {
      return NextResponse.json({ success: true, mode, removedKeys: keysToRemove });
    }

    const payload = parseSnapshotPayload(existing.payload);
    keysToRemove.forEach((key) => {
      delete payload[key];
    });

    if (Object.keys(payload).length === 0) {
      await prisma.userProgressSnapshot.delete({ where: { userId } });
    } else {
      await prisma.userProgressSnapshot.update({
        where: { userId },
        data: { payload: payload as Prisma.InputJsonValue },
      });
    }

    return NextResponse.json({ success: true, mode, removedKeys: keysToRemove });
  } catch (error) {
    console.error('Progress DELETE error:', error);
    return NextResponse.json(
      { success: false, error: 'Falha ao limpar progresso da conta.' },
      { status: 500 }
    );
  }
}

