import assert from 'node:assert';
import { autoRescheduleBacklog } from '../src/services/backlogRescheduler';
import type { StudyBlock, Subject } from '../src/types';

const toDateKey = (date: Date) =>
  `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(
    date.getDate()
  ).padStart(2, '0')}`;

const makeSubject = (id: string, priority: number, difficulty: number, pesoNoExame: number): Subject => ({
  id,
  userId: 'user-1',
  name: `Subject ${id}`,
  color: '#00B4FF',
  icon: 'book',
  area: 'geral',
  priority,
  difficulty,
  pesoNoExame,
  targetHours: 10,
  completedHours: 0,
  totalHours: 0,
  sessionsCount: 0,
  averageScore: 0,
  isActive: true,
  createdAt: new Date('2026-01-01T00:00:00'),
  updatedAt: new Date('2026-01-01T00:00:00'),
});

const makeBlock = (params: {
  id: string;
  date: Date;
  startTime: string;
  durationMinutes: number;
  subject: Subject;
  status?: StudyBlock['status'];
  type?: StudyBlock['type'];
  rescheduleCount?: number;
}): StudyBlock => {
  const [startHour, startMinute] = params.startTime.split(':').map(Number);
  const end = new Date(params.date);
  end.setHours(startHour, startMinute + params.durationMinutes, 0, 0);
  const endTime = `${String(end.getHours()).padStart(2, '0')}:${String(end.getMinutes()).padStart(2, '0')}`;

  return {
    id: params.id,
    userId: 'user-1',
    subjectId: params.subject.id,
    subject: params.subject,
    date: new Date(params.date),
    startTime: params.startTime,
    endTime,
    durationMinutes: params.durationMinutes,
    status: params.status ?? 'scheduled',
    isBreak: false,
    isAutoGenerated: true,
    type: params.type ?? 'AULA',
    description: undefined,
    sequenceIndex: undefined,
    relatedSubjectId: undefined,
    originalDate: new Date(params.date),
    completedAt: undefined,
    rescheduleCount: params.rescheduleCount ?? 0,
    createdAt: new Date('2026-01-01T00:00:00'),
    updatedAt: new Date('2026-01-01T00:00:00'),
  };
};

(() => {
  const today = new Date('2026-03-09T00:00:00');
  const yesterday = new Date('2026-03-08T00:00:00');
  const twoDaysAgo = new Date('2026-03-07T00:00:00');
  const tomorrow = new Date('2026-03-10T00:00:00');

  const subjHeavy = makeSubject('heavy', 10, 8, 5);
  const subjMedium = makeSubject('medium', 7, 6, 3);

  const overdueReview = makeBlock({
    id: 'overdue-review',
    date: yesterday,
    startTime: '09:00',
    durationMinutes: 50,
    subject: subjHeavy,
    status: 'scheduled',
    type: 'REVISAO',
  });
  const overdueLesson = makeBlock({
    id: 'overdue-lesson',
    date: twoDaysAgo,
    startTime: '10:00',
    durationMinutes: 50,
    subject: subjMedium,
    status: 'scheduled',
    type: 'AULA',
  });
  const todayPlannedA = makeBlock({
    id: 'today-a',
    date: today,
    startTime: '09:00',
    durationMinutes: 50,
    subject: subjMedium,
    status: 'scheduled',
    type: 'AULA',
  });
  const todayPlannedB = makeBlock({
    id: 'today-b',
    date: today,
    startTime: '10:00',
    durationMinutes: 50,
    subject: subjHeavy,
    status: 'scheduled',
    type: 'EXERCICIOS',
  });

  const capacityMap = {
    [toDateKey(today)]: 180,
    [toDateKey(tomorrow)]: 180,
  };

  const result = autoRescheduleBacklog({
    blocks: [overdueReview, overdueLesson, todayPlannedA, todayPlannedB],
    today,
    dailyLimitByDate: capacityMap,
    backlogQuotaRatio: 0.35,
    lookaheadDays: 2,
  });

  assert.ok(result.movedCount > 0, 'should move at least one backlog block');
  assert.ok(result.insertedTodayCount >= 1, 'should insert backlog into today');

  const todayBlocks = result.blocks
    .filter((block) => toDateKey(new Date(block.date)) === toDateKey(today))
    .sort((a, b) => a.startTime.localeCompare(b.startTime));
  assert.ok(todayBlocks.length > 0, 'today should still have blocks');
  assert.strictEqual(todayBlocks[0].id, 'overdue-review', 'overdue review should be inserted first');

  const todayBacklogMinutes = todayBlocks
    .filter((block) => block.status === 'rescheduled')
    .filter((block) => {
      const original = block.originalDate ? toDateKey(new Date(block.originalDate)) : toDateKey(new Date(block.date));
      return original < toDateKey(today);
    })
    .reduce((sum, block) => sum + block.durationMinutes, 0);
  assert.ok(todayBacklogMinutes <= Math.floor(capacityMap[toDateKey(today)] * 0.4), 'should respect daily backlog quota');

  const uniqueIds = new Set(result.blocks.map((block) => block.id));
  assert.strictEqual(uniqueIds.size, result.blocks.length, 'should not duplicate block ids');
})();

(() => {
  const today = new Date('2026-03-09T00:00:00');
  const tomorrow = new Date('2026-03-10T00:00:00');
  const heavy = makeSubject('recovery', 10, 9, 5);

  const stuck = makeBlock({
    id: 'stuck',
    date: new Date('2026-03-06T00:00:00'),
    startTime: '09:00',
    durationMinutes: 120,
    subject: heavy,
    status: 'rescheduled',
    type: 'AULA',
    rescheduleCount: 4,
  });

  const result = autoRescheduleBacklog({
    blocks: [stuck],
    today,
    dailyLimitByDate: {
      [toDateKey(today)]: 120,
      [toDateKey(tomorrow)]: 120,
    },
    backlogQuotaRatio: 0.35,
    lookaheadDays: 2,
  });

  const recoveryParts = result.blocks.filter((block) => block.description?.includes('Recuperacao'));
  assert.ok(recoveryParts.length >= 2, 'recovery mode should split stuck block into micro-blocks');
  assert.ok(recoveryParts.every((block) => block.durationMinutes <= 40), 'micro-blocks should be shorter');
  assert.ok(result.suggestion.shouldSuggestRecoveryMode, 'should suggest recovery mode when splitting backlog');

  const uniqueIds = new Set(result.blocks.map((block) => block.id));
  assert.strictEqual(uniqueIds.size, result.blocks.length, 'split blocks must keep unique ids');
})();

console.log('backlog rescheduler tests passed');
